/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class file_Filess */

#ifndef _Included_file_Filess
#define _Included_file_Filess
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     file_Filess
 * Method:    createMethod
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_file_Filess_createMethod
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     file_Filess
 * Method:    stringMethod
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_file_Filess_stringMethod
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     file_Filess
 * Method:    deleteMethod
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_file_Filess_deleteMethod
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
